export const STORIES_SHEET_NAME = "Stories";
export const STORIES_SPREADSHEET_ID =
  "1RwanzeTqzIvt-hQuSXdYZ0CtH0iDNIE3YbiVQ4ANqyE";

export const FAQS_SHEET_NAME = "FAQs";
export const FAQS_SPREADSHEET_ID =
  "1JvoZSZAPaRl-UJehW941bgCWUrtE_zHbL8NCCYpmR-E";

export const BOARD_MEMBERS_SHEET_NAME = "Sheet1";
export const BOARD_MEMBERS_SPREADSHEET_ID =
  "1HfdYszrs0aDR-45vCl6szSq3XP98hWXeXpmoK2FO5O0";

export const QUIZ_SHEET_NAME = "Sheet1";
export const QUIZ_SPREADSHEET_ID =
  "1Re-BFO4BlCeeCcXFQDuFqdtoJjnTgVwX0TXSyQAG3lE";

export const DATA_SOURCES = {
  STORIES: {
    STORIES_SPREADSHEET_ID,
    STORIES_SHEET_NAME,
  },
  FAQs: {
    FAQS_SPREADSHEET_ID,
    FAQS_SHEET_NAME,
  },
  BOARD_MEMBERS: {
    BOARD_MEMBERS_SPREADSHEET_ID,
    BOARD_MEMBERS_SHEET_NAME,
  },
  GAMES: {
    QUIZ: {
      QUIZ_SPREADSHEET_ID,
      QUIZ_SHEET_NAME,
    },
  },
};
