/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/generate-locale-route-manifest.mjs — do not edit.
 * Regenerate after adding/removing routes under src/app/[locale]:
 *   pnpm run sitemap:manifest
 */

export const LOCALE_STATIC_PATHS = [
  "",
  "activities-and-milestones",
  "beit-sagheer",
  "donate",
  "faqs",
  "fatwa",
  "kafala-blogs",
  "kafala-steps",
  "partnerships",
  "resources",
  "stock-donation",
  "vision-mission",
  "what-is-kafala",
  "who-we-are",
  "yk-gala"
] as const;

export const LOCALE_DYNAMIC_ROUTE_KEYS = [
  "kafala-blogs/[id]",
  "resources/[slug]"
] as const;
