const PrivacyPolicyPage = ({
  params: { locale },
}: {
  params: { locale: string };
}) => {
  return (
    <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold text-gray-900 mb-8">Privacy Policy</h1>
      <div className="text-gray-600 space-y-6">
        <div className="text-sm text-gray-500">
          Last updated: February 19, 2025
        </div>

        <section className="space-y-4">
          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">
            Interpretation and Definitions
          </h2>

          <div>
            <h3 className="text-xl font-medium text-gray-900 mb-2">
              Interpretation
            </h3>
            <p>
              The words of which the initial letter is capitalized have meanings
              defined under the following conditions. The following definitions
              shall have the same meaning regardless of whether they appear in
              singular or in plural.
            </p>
          </div>

          <div>
            <h3 className="text-xl font-medium text-gray-900 mb-2">
              Definitions
            </h3>
            <div className="space-y-2">
              <p>
                <strong>Account:</strong> means a unique account created for You
                to access our Service or parts of our Service.
              </p>
              <p>
                <strong>Affiliate:</strong> means an entity that controls, is
                controlled by or is under common control with a party, where
                "control" means ownership of 50% or more of the shares, equity
                interest or other securities entitled to vote for election of
                directors or other managing authority.
              </p>
              <p>
                <strong>Company:</strong> (referred to as either "the Company",
                "We", "Us" or "Our" in this Agreement) refers to Yalla Kafala,
                15 Onondaga Ave, San Francisco, California.
              </p>
              <p>
                <strong>Cookies:</strong> are small files that are placed on
                Your computer, mobile device or any other device by a website,
                containing the details of Your browsing history on that website
                among its many uses.
              </p>
              <p>
                <strong>Country:</strong> refers to: California, United States
              </p>
              <p>
                <strong>Device:</strong> means any device that can access the
                Service such as a computer, a cellphone or a digital tablet.
              </p>
              <p>
                <strong>Personal Data:</strong> is any information that relates
                to an identified or identifiable individual.
              </p>
              <p>
                <strong>Service:</strong> refers to the Website.
              </p>
              <p>
                <strong>Service Provider:</strong> means any natural or legal
                person who processes the data on behalf of the Company.
              </p>
              <p>
                <strong>Usage Data:</strong> refers to data collected
                automatically, either generated by the use of the Service or
                from the Service infrastructure itself.
              </p>
              <p>
                <strong>Website:</strong> refers to Yalla Kafala, accessible
                from https://www.yallakafala.org/
              </p>
              <p>
                <strong>You:</strong> means the individual accessing or using
                the Service, or the company, or other legal entity on behalf of
                which such individual is accessing or using the Service.
              </p>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">
            Collecting and Using Your Personal Data
          </h2>

          <div>
            <h3 className="text-xl font-medium text-gray-900 mb-2">
              Types of Data Collected
            </h3>

            <div className="space-y-4">
              <div>
                <h4 className="text-lg font-medium text-gray-900">
                  Personal Data
                </h4>
                <p>
                  While using Our Service, We may ask You to provide Us with
                  certain personally identifiable information that can be used
                  to contact or identify You. Personally identifiable
                  information may include, but is not limited to:
                </p>
                <ul className="list-disc list-inside ml-4 mt-2">
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Usage Data</li>
                </ul>
              </div>

              <div>
                <h4 className="text-lg font-medium text-gray-900">
                  Usage Data
                </h4>
                <p>
                  Usage Data is collected automatically when using the Service.
                  Usage Data may include information such as:
                </p>
                <ul className="list-disc list-inside ml-4 mt-2">
                  <li>
                    Your Device's Internet Protocol address (e.g. IP address)
                  </li>
                  <li>Browser type and version</li>
                  <li>Pages of our Service that You visit</li>
                  <li>Time and date of Your visit</li>
                  <li>Time spent on pages</li>
                  <li>Unique device identifiers and other diagnostic data</li>
                </ul>
              </div>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">
            Tracking Technologies and Cookies
          </h2>
          <p>
            We use Cookies and similar tracking technologies to track the
            activity on Our Service and store certain information. Tracking
            technologies used are beacons, tags, and scripts to collect and
            track information and to improve and analyze Our Service.
          </p>

          <div className="space-y-2">
            <p>
              <strong>Cookies or Browser Cookies:</strong> A cookie is a small
              file placed on Your Device. You can instruct Your browser to
              refuse all Cookies or to indicate when a Cookie is being sent.
            </p>
            <p>
              <strong>Web Beacons:</strong> Certain sections of our Service and
              our emails may contain small electronic files known as web beacons
              that permit the Company to count users who have visited those
              pages or opened an email.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-xl font-medium text-gray-900">
              Types of Cookies We Use:
            </h3>
            <div className="ml-4 space-y-4">
              <div>
                <h4 className="font-medium">Necessary / Essential Cookies</h4>
                <p>Type: Session Cookies</p>
                <p>
                  Purpose: These Cookies are essential to provide You with
                  services available through the Website and to enable You to
                  use some of its features.
                </p>
              </div>

              <div>
                <h4 className="font-medium">Functionality Cookies</h4>
                <p>Type: Persistent Cookies</p>
                <p>
                  Purpose: These Cookies allow us to remember choices You make
                  when You use the Website, such as remembering your login
                  details or language preference.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">
            Use of Your Personal Data
          </h2>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul className="list-disc list-inside ml-4 space-y-2">
            <li>To provide and maintain our Service</li>
            <li>To manage Your Account</li>
            <li>For the performance of a contract</li>
            <li>To contact You</li>
            <li>To provide You with news and offers</li>
            <li>To manage Your requests</li>
            <li>For business transfers</li>
            <li>For other purposes such as data analysis</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-gray-900">Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, You can contact
            us by visiting this page on our website:{" "}
            <a
              href="https://www.yallakafala.org/en/contact_us"
              className="text-blue-600 hover:text-blue-800"
            >
              https://www.yallakafala.org/en/contact_us
            </a>
          </p>
        </section>
      </div>
    </div>
  );
};

export default PrivacyPolicyPage;
